### ISSUE TITLE
Preparar Apresentação para Release 01

### ISSUE THREAD

**Issue by victoralvesgomide** [fga-eps-mds/2019.2-Vsign#101]
**Descrição**

- [x] Estruturar apresentação em tópicos;
- [x] Delegar tópicos para a equipe de desenvolvimento (MDS);
- [x] Montar apresentação de slides no Google Sheets;
- [x] *[MDS]* Estudar e se preparar para apresentar parte a qual lhe foi delegado;
- [x] *[EPS]* Instruir sobre conceitos de gestão e sua importância.

**Comment by victoralvesgomide** [comment]
**ESTRUTURA DA APRESENTAÇÃO**
- Visão de Produto
  * Equipe
  * Problema
  * Solução
  * Escopo
  * Diagrama de classes
  * Diagrama de casos de uso
  * Protótipo de "média fidelidade”

- Viabilidade do Projeto
  * Gestão da equipe
    - Metodologia
    - Ferramentas
    - Roadmaps
    - Métricas
    - Riscos
  * Arquitetura
  * Cobertura de testes
  * "Show Me the Code"

**Comment by victoralvesgomide** [comment]
* Visão de Produto: @williamtpv 
  - Auxiliar: P.O. ( @caue96 )
* Diagrama de Classe + Casos de Uso + Protótipo: @ViniciusPuerto 
  - Auxiliar: P.O. ( @caue96 ) & S.M. ( @victoralvesgomide )
* Gestão da Equipe: @marcosgtavares 
  - Auxiliar: S.M. ( @victoralvesgomide )
* Arquitetura + Cobertura de Teste: @Foxtrot40 
  - Auxiliar: Arquiteto ( @kairon-v ) & DevOps ( @thiagorpereira )
* O que implementamos até agora: @MarcosFloresta 
  - Auxiliar: Todos de EPS

**Comment by ViniciusPuerto** [comment]
### Link para apresentação 

Segue o link para a [apresentação](https://docs.google.com/presentation/d/1NSdRW3vxKmkkLgV_WGvosaD-DRenYV1YcN-5pwiAISw/edit#slide=id.g63027e2093_1_148) que usamos para a release 01
