### ISSUE TITLE
Upload do áudio de assinatura

### ISSUE THREAD

**Issue by kairon-v** [fga-eps-mds/2019.2-Vsign#122]
**Descrição**
Como usuário, preciso que as imagens tomadas de minha face, durante a gravação do vídeo de assinatura, sejam enviadas para nuvem para que sejam utilizadas para o facematch.

**Critérios de aceite**
- [x] O aúdio deve ser armazenadas na S3.
- [x] Deve ser utilizado GraphQL para upload.
- [x] Converter aúdio para o formato desejado pelo S2T.
- [ ] O processo de upload do áudio deve levar em consideração a experiência de usuário (UX). Portanto, as alterações na UI devem ser feitas conforme necessárias.

**Comment by kairon-v** [comment]
Seguir o artigo abaixo para o critério do upload com GraphQL

https://evilmartians.com/chronicles/active-storage-meets-graphql-direct-uploads

**Comment by ViniciusPuerto** [comment]
### Quanto à conversão do áudio 

Na nossa aplicação ao gravar o vídeo também gravamos o áudio no formato WebM porém a biblioteca do Google não lê esse formato e existem algumas soluções para conversão e uma delas é no backend que evitaria trabalho via client-side, uma biblioteca que faz isso é o FFmpeg

```
ffmpeg -i input.webm output.m4a
ffmpeg -i input.ogg output.m4a
```
ela funcionaria da seguinte forma porém teríamos que ver como fazer no ruby.

**Comment by kairon-v** [comment]
Foi implementado o upload do áudio. O último critério ainda não foi atendido porque precisa apresentar informações dos diferentes tipos de arquivos que são enviados. Será aberta outra issue para atender este critério pendente.
