### ISSUE TITLE
Extrair informações do documento do usuário

### ISSUE THREAD

**Issue by kairon-v** [fga-eps-mds/2019.2-Vsign#123]
**Descrição**
Como usuário, desejo que as informações do documento que enviei para a plataforma sejam extraídas para a validação da minha assinatura.

**Critérios de aceite**
- [x] Usar AWS Rekognition;
- [x] Organizar informações extraídas de maneira apropriada para facilitar a validação dos dados.

A documentação a ser seguida está disponível em: https://docs.aws.amazon.com/rekognition/latest/dg/API_DetectText.html

**Comment by caue96** [comment]
Pull Request está sendo fechado, pois já existe outro PR aberto com a mesma finalidade e onde está sendo desenvolvida essa fucnionalidade (#137)
