### ISSUE TITLE
Autenticar Usuário

### ISSUE THREAD

**Issue by kairon-v** [fga-eps-mds/2019.2-Vsign#124]
**Descrição**

Como usuário, preciso me autenticar na plataforma do Vsign para gerenciar os contratos e assinaturas.

**Critérios de aceite**
- [x] Integrar página de login com backend via GraphQL
- [x] Bloquear acesso de usuários não autenticados a páginas restritas
- [ ] Permitir autenticação com token (para login sem usuário e senha, direto do email)

> ***DÍVIDA TÉCNICA DESDE A SPRINT 7***

**Comment by Foxtrot40** [comment]
Quais são essas páginas restritas?

**Comment by kairon-v** [comment]
1. Criar rota no frontend `/sign/:token`, onde `:token` é o token do contrato.
2. Criar mutation no GraphQL para fazer o login.

````
mutation DirectLogin {
    directLogin(token: 'MY_TOKEN') {
      token
    }
}
```
Essa mutation irá fazer o login do usuário, quando ele entrar na URL acima. O token retornado, é o token JWT criado para chamadas subsequentes na API.

**Comment by kairon-v** [comment]
Implementado em #161 e melhorado em #163 .
