### ISSUE TITLE
BUG124 - Autenticar Usuário

### ISSUE THREAD

**Issue by Foxtrot40** [fga-eps-mds/2019.2-Vsign#126]
**Descrição**
Ao rodar ```docker-compose up``` na pasta backend ele da o erro ```ERROR: Couldn't find env file: /home/marcos/Documents/unb/mds/vsign/backend/backend/app.env```. Como da pra ver no log, o erro se encontra no caminho que está apontado para o arquivo app.env no arquivo docker-compose.yml em env_file, que deveria ser ```./app.env``` ao invés de ```./backend/app.env```.

**Passo a Passo**
Passo a passo para se reproduzir o bug:
1. Entrar na pasta backend
2. Rodar ```docker-compose up```
3. Ver o erro

**Comportamento Esperado**
Conseguir rodar o container com as variaveis de ambiente que estão em app.env.

**Screenshots**
Rodando o comando ```docker-compose build``` na pasta backend (com ```docker-compose up``` da no mesmo):
![bug](https://user-images.githubusercontent.com/24324267/67137874-5cb1cc80-f212-11e9-9b82-a1e8826e2a72.png)

**Informações do Desktop:**
 - OS: Ubuntu
 - Versão do OS: 16.04 LTS
 - Browser: Não se aplica
 - Versão do Browser: Não se aplica

**Comment by kairon-v** [comment]
Problema corrigido no #163 .
