### ISSUE TITLE
Treinamento de Docker

### ISSUE THREAD

**Issue by caue96** [fga-eps-mds/2019.2-Vsign#13]
### **Descrição**
Introduzir ao time os conceitos básicos de docker, mostrar na prática como ele funciona e iniciar configuração do docker no projeto.

**Comment by thiagorpereira** [comment]
Durante a reunião do dia 31/08 (sábado), 8 integrantes estiveram presente no treinamento em uma sala reservada na BCE, Darcy Ribeiro, onde foi:

- Introduzido as vantagens dos Containers em contraste com as VM
- Uma breve história do Docker 
- Treinamento prático de Docker e Docker Compose
- Comandos básicos e respectivas definições.

Foi utilizado o Quickstart: Compose and Rails para exercício e explicação de conceitos.
https://docs.docker.com/compose/rails/

Fontes e Materiais para estudo:
https://docs.docker.com/compose/
https://blog.netapp.com/blogs/containers-vs-vms/
https://www.backblaze.com/blog/vm-vs-containers/
https://www.youtube.com/watch?v=0xxHiOSJVe8&list=PLf-O3X2-mxDkiUH0r_BadgtELJ_qyrFJ_
