### ISSUE TITLE
Integração e Deploy contínuos da documentação

### ISSUE THREAD

**Issue by victoralvesgomide** [fga-eps-mds/2019.2-Vsign#132]
As alterações de documentação na branch "master" devem automaticamente estar disponíveis no ambiente de produção de documentação.

**Comment by thiagorpereira** [comment]
Para realizar o [Deploy no Mkdocs](https://www.mkdocs.org/user-guide/deploying-your-docs/), no diretório onde estiver mkdocs.yml, deve rodar o comando:

$ mkdocs gh-deploy  

Para automaticar o processo utilizando nossa CI siga os passos:

Como precisa de uma autentificação do github para realizar o deploy, é necessaŕio gerar uma [SSH key](https://help.github.com/en/enterprise/2.17/user/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent)

Será gerada uma chave publica e outra privada;
* A chave privada deve ser inserida no CircleCI do projeto e então será gerado um fingersprint que será utilizado no config.yml; 
* A chave publica, deve-se realizar um upload da mesma no Deploy Keys no GitHub do projeto para de fato ocorrer a conexão

E no config.yml deve instalar e configurar as dependencias , setar a fingersprint, fazer o build do mkdocs e realizar o deploy

**Comment by caue96** [comment]
Deploy contínuo da documentação foi implementado e está funcionando perfeitamente. Parabéns @thiagorpereira
