### ISSUE TITLE
Treinamento de Metodologia

### ISSUE THREAD

**Issue by caue96** [fga-eps-mds/2019.2-Vsign#14]
### **Descrição**
Explicar para o time a metodologia Agile e explicar os framework Scrum e XP que serão utilizadas durante o projeto.

**Comment by victoralvesgomide** [comment]
* Expliquei sobre Sprints e o fluxo básico do Scrum;
* Expliquei sobre os papéis e como eu, como Scrum Master, poderia ajudá-los;
* Expliquei o funcionamento e a importância de cada um dos rituais do Scrum;
* Expliquei o que é um Kanban e como utilizaríamos na disciplina por meio do ZenHub;
* Expliquei sobre o XP e citei algumas das boas práticas que ele prega, como o pareamento.

**Fontes utilizadas:**
[Heflo - Metodologia Ágil Scrum](https://www.heflo.com/pt-br/agil/metodologia-agil-scrum/)  
[DevMedia - Integrando XP às principais metodologias ágeis](https://www.devmedia.com.br/integrando-xp-as-principais-metodologias-ageis/30989)
