### ISSUE TITLE
Matching do audio com o roteiro

### ISSUE THREAD

**Issue by kairon-v** [fga-eps-mds/2019.2-Vsign#141]
**Descrição**<br>
Essa descrição vai indicar o autor da ação, funcionalidade desejada e o valor agregado pela funcionalidade.

**Critérios de aceite**
- [x] Utilizar algum método para validar se o texto extraído do áudio está de acordo com o roteiro.

**Comment by ViniciusPuerto** [comment]
Está sendo usado o algoritmo de comparação de strings[ Jaro Winkler](https://medium.com/@appaloosastore/string-similarity-algorithms-compared-3f7b4d12f0ff)

**Comment by kairon-v** [comment]
#184
