### ISSUE TITLE
Extrair texto do áudio

### ISSUE THREAD

**Issue by kairon-v** [fga-eps-mds/2019.2-Vsign#143]
**Descrição**<br>
Essa descrição vai indicar o autor da ação, funcionalidade desejada e o valor agregado pela funcionalidade.

**Critérios de aceite**
- [x] Utilizar Speech to Texto do Google Cloud Plataform
- [x] Extrair texto do áudio de assinatura.
- [x] Armazenar o texto extraído na model `Contract` em um campo do tipo `string` com o título `detected_text`.

**Comment by ViniciusPuerto** [comment]
### Problemas 

Estou com problemas pois ao rodar o script que extrai o texto do áudio que gravamos em nosso app ele não retorna nenhum resultado, porém se eu uso ele no próprio [site](https://cloud.google.com/speech-to-text/) do Speech2Text ele retorna o resultado esperado e usando as mesmas configurações do meu código. Minha principal suspeita é que o áudio que é gravado pelo browser não possui os [encodings compatíveis](https://cloud.google.com/speech-to-text/docs/encoding).

**Comment by kairon-v** [comment]
#184
