### ISSUE TITLE
Estudos sobre as tecnologias que serão utilizadas no projeto

### ISSUE THREAD

**Issue by caue96** [fga-eps-mds/2019.2-Vsign#15]
### **Descrição**
Estudos realizados por toda a equipe com relação as tecnlogias que serão utilizadas no projeto. Fontes dos estudos e pontos mais importantes de cada fonte deverão ser colocados nessa issue.

**Comment by caue96** [comment]
### Estudos em Leitura
- [Ruby On Rails](https://guides.rubyonrails.org/)
- [React](https://pt-br.reactjs.org/docs/getting-started.html)
- [Amazon S3](https://pt-br.reactjs.org/docs/getting-started.html)
- [Amazon Rekognition](https://aws.amazon.com/pt/rekognition/resources/?nc=sn&loc=6)
- [Google Speech to Text API](https://cloud.google.com/speech-to-text/docs/)
- [GraphQL](https://graphql.org/learn/)

**Comment by caue96** [comment]
Para aqueles da equipe de MDS que precisam aprender um pouco mais sobre git, segue 3 fontes com bons tutoriais para estudar:

- [Documentação Git](https://git-scm.com/doc)
- [Tutorial Git](http://www.devfuria.com.br/git/tutorial-iniciando-git/)
- [Guia prático Git](https://rogerdudler.github.io/git-guide/index.pt_BR.html)

**Comment by Foxtrot40** [comment]
[Documentação da Gem que implementa o GraphQL](https://graphql-ruby.org/getting_started.html) para aprender como criar os "controllers" do graphql.

**Comment by ViniciusPuerto** [comment]
### Artigos de UX

- 30 boas dicas para usar o Adobe Xd => [Adobe XD — 30 Tips & Tricks you wish you’d known earlier!](https://medium.com/@learnux.io/adobe-xd-30-tips-tricks-you-wish-youd-known-earlier-54bd117b2eb7) 

- Designs que não são tão bons de se usar => [Misused mobile UX patterns](https://medium.com/@kollinz/misused-mobile-ux-patterns-84d2b6930570)

**Comment by ViniciusPuerto** [comment]
### Dicas sobre posicionamento usando Flex
Segue no link as melhores formas de posicionar elementos numa página usando  [FlexBox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/)

**Comment by Foxtrot40** [comment]
# Curso Gratuito de Ruby No Darcy
O Ramo Estudantil do IEEE vai ofertar um curso de Ruby lá no Darcy. É uma galera legal que ensina bem, à quem interessar, segue o link

[Site do evento](http://bit.ly/cronograma-seneieeeweek)

**Comment by Foxtrot40** [comment]
[Playlist legal de GraphQL pra quem quiser](https://www.youtube.com/watch?v=GAl2EIQVG_g&list=PLYRxaDweTODWIDgAboxLqQ5adD3ZrcDbs&index=2)
### <strong>é em inglês</strong>.

**Comment by Foxtrot40** [comment]
Webinar de devops dia 15/10 online [aqui](https://universidadedevops.com.br/ls6-masterclass-a421/)

**Comment by ViniciusPuerto** [comment]
# Primeiro teste usando Speech-to-text

Usei este [link](https://cloud.google.com/speech-to-text/docs/sync-recognize#speech-sync-recognize-ruby) como base para gerar um script em ruby com um arquivo de [áudio que baixei](https://speechnotes.co/files/assets/pro.mp3).

Para rodar o script basta importar corretamente as chaves da API do Google e em seguida executá-lo. 
 
### Importando a biblioteca 

``` require "google/cloud/speech" ```

### Instanciando o client

``` speech = Google::Cloud::Speech.new ```

### Lendo o arquivo e pegando seu raw

```
file_name = "./flacfile.flac"
audio_file = File.binread file_name 
 ```

### Configurando o reconhecimento

```
config = { encoding:          :FLAC,
          audio_channel_count: 2,
           language_code:     "en-US" }
audio  = { content: audio_file }
```

Nesse passo é importando você converter seu audio para  ``` .FLAC ``` e usei esse [site](https://www.aconvert.com/audio/)

### Detectando e printando a saída

```
response = speech.recognize(config, audio)
puts response.results
```

## Saída obtida

A saída que obtive foi a seguinte :
![image](https://user-images.githubusercontent.com/26886701/66280554-9d622b00-e88d-11e9-8f58-119ac64c5cf1.png)

**Comment by Foxtrot40** [comment]
Tutorial de redux com react https://www.robinwieruch.de/local-storage-react

**Comment by Foxtrot40** [comment]
Não sobre as tecnologias mas sobre o modelo de negócios, tem esse [podcast sobre a LGPD](https://hipsters.tech/lgpd-lei-geral-de-protecao-de-dados-hipsters-174/), com a presença de alguns advogados, que falam sobre como essa lei afeta as empresas dando uma resumida

**Comment by caue96** [comment]
Todos os estudos realizados durante o projeto foram finalizados.
