### ISSUE TITLE
Criar uma forma de popular o banco

### ISSUE THREAD

**Issue by ViniciusPuerto** [fga-eps-mds/2019.2-Vsign#152]
**Descrição**<br>
Criar alguma forma de popular o banco de dados com usuários, empresas e um contrato por usuário.

**Comment by ViniciusPuerto** [comment]
### Recomendações 

Recomendo usar a gem [faker](https://github.com/faker-ruby/faker) para popular os dados.

**Comment by kairon-v** [comment]
Implementado em #153 .
