### ISSUE TITLE
Remover docker-compose geral

### ISSUE THREAD

**Issue by kairon-v** [fga-eps-mds/2019.2-Vsign#154]
**Descrição**<br>
Sugiro remover o docker-compose geral (para os dois projetos) e deixar apenas o de backend e o de frontend separados.

A existência de ambos faz com que ocorra de forma constante conflitos relacionados a build dos containers, instalação de novas libs, etc.

**Comment by thiagorpereira** [comment]
Foi abordado o tema durante a reunião semanal; Apesar de eventuais complicações locais e da demora da build de todas as dependencias e do levantamento do ambiente do mesmo, é preferível que todos integranes adotem o levantamento do docker-compose isolado, backend e frontend; 
* Obs: O docker-compose geral permanecerá por ser mais intuitivo para um terceiro levantar o ambiente do projeto, inclui a comunidade, monitores e avaliadores da disciplina
