### ISSUE TITLE
Corrigir gravação do áudio para upload

### ISSUE THREAD

**Issue by kairon-v** [fga-eps-mds/2019.2-Vsign#155]
**Descrição**<br>
Acredito que há problemas com a biblioteca utilizada para gravação do áudio que está impossibilitando o upload bem com a extração do texto no speech2text.

**Comportamento Esperado**<br>
Gravação de áudio de maneira que possa ser feito o upload e a extração do texto.

**Comment by ViniciusPuerto** [comment]
### Possivel erro

Após analises, junto ao time foi criada a hipótese de que o problema está na falta de metadados no arquivo de blob/áudio que deve ser upado e processado pela biblioteca.
Uma solução pode ser a adoção de outra forma de gravação.

**Comment by kairon-v** [comment]
#163
