### ISSUE TITLE
Não enviando email de novo contrato

### ISSUE THREAD

**Issue by kairon-v** [fga-eps-mds/2019.2-Vsign#166]
**Descrição**<br>
O email que deveria ser enviado para o usuário no momento da criação de novos contratos não está sendo enviado.

**Passo a Passo**<br>
Passo a passo para se reproduzir o bug:
1. Criar um contrato através da API;
2. Deveria ter recebido a mensagem por email.

**Comportamento Esperado**<br>
Deveria ter sido enviado um email para o usuário

**Comment by Foxtrot40** [comment]
Na funcão de criar novo contrato não chama a função de enviar email

**Comment by kairon-v** [comment]
Corrigido em #181
