### ISSUE TITLE
Documentar fluxo de usuário na aplicação

### ISSUE THREAD

**Issue by kairon-v** [fga-eps-mds/2019.2-Vsign#169]
**Descrição**<br>
Deve se gerar um documento com imagens mostrando e explicando os possíveis fluxos do usuário na aplicação.

**Comment by caue96** [comment]
Ficou resolvido não subir um documento com o fluxo que o usuário deveria seguir dentro da aplicação, pois no readme já temos images com todas as telas da aplicação e dentro da aplicação nas etapas da assinatura de contrato já é apresentado para o usuário o passo a passo para finalizar toda a assinatura.
