### ISSUE TITLE
Criar protótipo de alta fidelidade

### ISSUE THREAD

**Issue by kairon-v** [fga-eps-mds/2019.2-Vsign#18]
### Descrição

Criaç!ao do protótipo de alta fidelidade da aplicação.

**Comment by Foxtrot40** [comment]
O protótipo deve ser criado junto ao cliente? Ou cria e depois apresenta pro cliente?

**Comment by ViniciusPuerto** [comment]
É nesse que usaremos aquelas ferramentas como adobe xd e etc?

**Comment by caue96** [comment]
@Foxtrot40 o protótipo será criado por toda a equipe de MDS e após pronto será apresentado para o cliente para validação.

@ViniciusPuerto sim, é nessa issue de criação do protótipo de alta fidelidade que vocês usarão essas ferramentas. Indico para vocês olharem [esse artigo no medium](https://medium.com/aela/quais-s%C3%A3o-as-melhores-ferramentas-de-prototipagem-de-interface-ui-ux-9b36155eef7a) onde tem ótimas opções de ferramentas.

**Comment by caue96** [comment]
Foi criado uma protótipo de "média" fidelidade (nem baixa e nem alta) e decidimos que ele seria nosso único protótipo feito, pois já tinha validado com o cliente e dali partimos para programação do visual do web-app.
