### ISSUE TITLE
Configurar ambiente de Documentação

### ISSUE THREAD

**Issue by thiagorpereira** [fga-eps-mds/2019.2-Vsign#23]
**Descrição** 

Configurar ambiente para inclusão de artefatos do projeto tal que seja criado um site estático a cada entrega sem que seja realizado configurações manuais de HTML, CSS e JS

**Critérios de aceitação**
- [x] Inicializar MKdocs project;
- [x] Utilizar GitHub Pages para hospedar a documentação;
- [x] Pasta /docs deve seguir a estrutura de pasta definida #2 .

**Comment by caue96** [comment]
Dívida Técnica para sprint 2.

**Comment by thiagorpereira** [comment]
Ela é uma branch gerada; Então ao rodar o comando (na raíz onde tem o mkdocs.yml): 
* mkdocs gh-deploy; 

Mesmo q rode o comando em qualquer branch, será armazenado os files css,js,html gerados na branch gh-pages; 

A gh-pages serve pra armazenar esses files gerados ao realizar o deploy
