### ISSUE TITLE
Onde colocar o "arquivo".md (markdown) escrito para o documento de visão dentro da estrutura de pastas da branch gh-pages

### ISSUE THREAD

**Issue by marcosgtavares** [fga-eps-mds/2019.2-Vsign#24]

**Comment by caue96** [comment]
Como estamos usando a branch master para atualizar a wiki do projeto enquanto estamos no início do projeto documentando, nós estamos criando branchs a partir da master e fazendo os commits nessa branch filha e quando estiver tudo pronto você da um push do documento na branch filha e logo após abre uma requisição de pull request da branch filha para a master.

Com relação a essa issue ela tem alguns erros que das próximas vezes não se poderá cometer mais. O texto que você colocou como comentário da issue deveria ter ido no campo de descrição da issue antes de criar a issue, seguindo um dos padrões já estabelecidos de issue (nesse caso seria o padrão custom). E quando fizer aberturas assim de issues de dúvidas você não deve se marcar, pois você não está resolvendo a issue, ou você deixa vazia ou da assignees para todas as pessoas que podem resolver seu problema e você sabe que eles terão capacidade de resolver.

**Comment by marcosgtavares** [comment]
Obrigado pelo esclarecimento e o mesmos erros cometido na issue não acontecera novamente.
