### ISSUE TITLE
Cheatsheet de Markdown

### ISSUE THREAD

**Issue by Foxtrot40** [fga-eps-mds/2019.2-Vsign#27]
**Descrição**
Nesse site tem um cheatsheet de markdown que pode ajudar a criar os documentos.
`https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#emphasis`

**Comment by caue96** [comment]
Todos do time utilizaram esses 2 links como referência para aprender Markdown e com isso essa issue está sendo fechada agora, podendo ser reaberta no futuro em caso de alguma atualização.
