### ISSUE TITLE
Elaborar treinamentos para equipe de desenvolvimento

### ISSUE THREAD

**Issue by kairon-v** [fga-eps-mds/2019.2-Vsign#3]
Elaborar os treinamentos iniciais para a equipe de desenvolvimento.

Treinamentos sugeridos:

- Docker
- Framework (a ser definido de acordo com o tema)
- Arquitetura (a ser definida)
- Metodologia de desenvolvimento do projeto

**Comment by caue96** [comment]
Treinamentos programados para serem dados no início do projeto:

| Treinamento | Responsável |
|         ---         |          ---         |
|      Docker     | @thiagorpereira |
|    GraphQL   |   @kairon-v   |
|       Rails       |   @kairon-v   |
|      React      |   @kairon-v    |
| Metodologia | @victoralvesgomide |
| Documentação |  @caue96 |
