### ISSUE TITLE
Fazer Protótipo de baixa fidelidade

### ISSUE THREAD

**Issue by caue96** [fga-eps-mds/2019.2-Vsign#36]
**Descrição**<br>
Fazer um protótipo de baixa fidelidade para dar uma visão mais homogenia do projeto entre o time de MDS.

**Comment by ViniciusPuerto** [comment]
### Link para o protótipo
Este é o link onde estou editando o protótipo no Adobe Xd : [Link de acompanhamento](https://xd.adobe.com/view/f2299288-7e64-41b9-63eb-c51d820d1e26-8418/)

**Comment by caue96** [comment]
Dívida Técnica para sprint 2.

**Comment by ViniciusPuerto** [comment]
### Link para protótipo , editável

[Link](https://xd.adobe.com/spec/d6ee789f-14c1-4f9e-7785-524cf38983a1-a0df/)
