### ISSUE TITLE
Fazer Diagrama de Classe

### ISSUE THREAD

**Issue by caue96** [fga-eps-mds/2019.2-Vsign#38]
**Descrição**<br>
Diagrama de classe para mostrar classes, atributos e as relações entre as classes do projeto.

**Comment by thiagorpereira** [comment]
Lógica de negócio da aplicação sendo discutida para realização do diagram de classes; com auxilio do arquiteto @kairon-v 

![photo5181942935741114469](https://user-images.githubusercontent.com/26577467/64904529-bec26380-d6a1-11e9-8a06-1e53f47979f3.jpg)

**Comment by caue96** [comment]
Dívida Técnica para sprint 2.
