### ISSUE TITLE
US01 - Mostrar Roteiro

### ISSUE THREAD

**Issue by caue96** [fga-eps-mds/2019.2-Vsign#39]
**Descrição**<br>
Como usuário eu quero poder visualizar o roteiro para saber qual o texto que deverá ser dito para assinatura do contrato.

**Critérios de aceite**
- [x] O roteiro deve ser apresentado em bloco durante a gravação do vídeo, para ficilitar a leitura do texto;
- [x] Deve possuir um botão para avançar para o próximo bloco;
- [x] Quando o roteiro for finalizado, deve ser apresentado um botão para finalizar a gravação.

**Comment by caue96** [comment]
Dívida Técnica para sprint 2.

**Comment by ViniciusPuerto** [comment]
Como essa tarefa era basicamente igual à da us02/#51 eu atribuí ela a mim
![image](https://user-images.githubusercontent.com/26886701/65297941-003e8d00-db40-11e9-8fec-bf00c61c1490.png)
**Código referente se encontrará na us02/#51**

**Comment by ViniciusPuerto** [comment]
Issue deve ser fechada pois ela era englobada na #51 que a mesma também já foi finalizada.
