### ISSUE TITLE
US02 - Gravar Vídeo de Assinatura

### ISSUE THREAD

**Issue by kairon-v** [fga-eps-mds/2019.2-Vsign#51]
**Descrição**

Como USUÁRIO, desejo gravar vídeo para realizar assinatura de contrato.

**Critérios de aceitação**

- [x] Solicitar permissão de uso do microfone e câmera;
- [x] Caso o usuário não autorize, a recusa deve ser tratada;
- [x] Gravar vídeo e áudio do usuário;
- [x] Sobre a imagem da câmera, deve ser mostrado um marcador quadrado para que o usuário tenha referência de onde deve-se posicionar para gravação do vídeo (conforme protótipo)'
- [x] Apresentar timer para mostrar ao usuário sobre a duração do vídeo;
- [x] Apresentar informação se o vídeo está sendo gravado ou não.

**Comment by kairon-v** [comment]
Nessa página, são apresentados alguns métodos para realizar a gravação utilizando JavaScript: [https://stackoverflow.com/questions/18509385/html-5-video-recording-and-storing-a-stream](https://stackoverflow.com/questions/18509385/html-5-video-recording-and-storing-a-stream)

**Comment by ViniciusPuerto** [comment]
### Design da tela a ser implementado

![tela de gravar](https://user-images.githubusercontent.com/26886701/64966841-e8cc7f00-d875-11e9-8306-3b8b157fecfa.png)

**Comment by ViniciusPuerto** [comment]
### Biblotecas que serão usadas
As seguintes bibliotecas estão sendo escolhidas para gravarmos o vídeo [videojs-record](https://github.com/collab-project/videojs-record) ou [react-video-recorder](https://github.com/fbaiodias/react-video-recorder)

**Comment by ViniciusPuerto** [comment]
### Link do trello

Criei um link no qual quebrei as funcionalidades em várias tarefas e separei em cards usando PDCA para cumprirmos os critérios de aceitação.
- [Link do quadro](https://trello.com/b/EOklfDyZ/my-mds)

**Comment by ViniciusPuerto** [comment]
### Duvida !!
Para fazermos o upload do video na API usaremos blob? 
Por exemplo, consegui gravar o video e ao printar o blob do vídeo no console tenho a seguinte saida: 
![image](https://user-images.githubusercontent.com/26886701/65295040-7c33d780-db36-11e9-91de-4ce47579cf93.png)

**Comment by kairon-v** [comment]
@ViniciusPuerto Isso mesmo!

**Comment by ViniciusPuerto** [comment]
### Status
A parte de gravação de vídeo e passar os blocos de roteiro foi finalizada, agora vamos extrair o áudio ou gravá-lo separadamente

**Comment by ViniciusPuerto** [comment]
### Link de auxilio e extração do áudio
Ao gravar o vídeo consigo obter um blob com media-type webm, que é um tipo de vídeo especifico para web, e para não termos que gravar o áudio separadamente pretendo extrair o áudio do vídeo, nos seguintes links do stackoverflow aparentemente conseguiram fazer isso porém não entendi muito bem, alguém puder me ajudar com isso?
- [Extracting audio from a video file](https://stackoverflow.com/questions/49140159/extracting-audio-from-a-video-file)
- [Get audio from HTML5 video](https://stackoverflow.com/questions/34984501/get-audio-from-html5-video)

**Comment by ViniciusPuerto** [comment]
### Audio gravado com sucesso 
Conforme a imagem do blob abaixo, conseguimos gravar o áudio do usuário.
![image](https://user-images.githubusercontent.com/26886701/65374265-5f92bf00-dc5e-11e9-82b9-dfb040dc7742.png)
