### ISSUE TITLE
US03 - Tirar fotos durante gravação de vídeo

### ISSUE THREAD

**Issue by kairon-v** [fga-eps-mds/2019.2-Vsign#52]
**Descrição**
Como usuário, desejo que sejam tomadas fotos de minha face durante a gravação do vídeo e em momentos específicos para realizar o face matching da assinatura.

**Critérios de aceite**
- [x] A primeira foto deve ser feita 2 segundos após o início da gravação;
- [x] As demais fotos devem ser feitas 2 segundos após o usuário avançar na leitura do roteiro.
- [x] As imagens devem ser armazenadas de forma que seja possível enviá-las para a API posteriormente.

**Comment by kairon-v** [comment]
Dicas

Pode se utilizada a função `setTimeout ` para realizar a tomada das imagens no momento correto.

Ex.: quando o usuário apertar o botão de iniciar a gravação, chama a `setTimeout ` com `2000` e executa a função para tirar a foto do usuário.

**Comment by ViniciusPuerto** [comment]
### Função usada 

A seguinte função foi usada para disparar as imagens:

``` 
this.player.on('timestamp', () => {
            console.log(this.player.currentTimeStamp);
            const signatureImageAux = this.state.signatureImage
            signatureImageAux.push(this.player.currentTimeStamp);
            this.setState({signatureImage: signatureImageAux});
            console.log("Log dos timeStamps\n" + this.state.signatureImage)
        })
```

Em que ``` this.player``` é o elemento responsável pela gravação e quando se usa o método ``` .on()```  e com o argumento ``` "timestamp" ``` significa que a cada dois segundos, valor definido nas propriedades do player, um TimeStamp é disparado.
