### ISSUE TITLE
US04 - Criar novos contratos

### ISSUE THREAD

**Issue by kairon-v** [fga-eps-mds/2019.2-Vsign#53]
**Descrição**<br>
Como empresa, desejo criar novos contratos para serem assinados via serviço da VSign por vídeo.

**Critérios de aceitação**
- [x] Criar endpoint utilizando conceitos `REST` para recebimento de informações do contrato;
- [x] Identificar empresa através de seu `CLIENT_ID`;
- [x] Realizar a montagem do roteiro conforme o template da empresa;
- [x] Criar usuário com senha aleatória e nome e email conforme enviado pela empresa, caso este não possua conta no VSign (considerar existência do email)

**Comment by kairon-v** [comment]
**Dicas**

Pode ser utilizado o seguinte exemplo para levar em consideração na criação de novos contratos.

```
curl --location
  --request POST "https://api.vsign.com.br/v1/contracts/" 
  --header "Content-Type: application/json" 
  --data "{
	"order": "ABCDEFZP",
        "name": "Fulano de Tal",
	"email": "fulano@email.com",
        "client_id": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6ImFtb2VkbyIsImV4cCI6MTU2MjQyMTc1NSwiZW1haWwiOm51bGx9.un3L-hiVI9NVM-Xg_I-dPkvpbsa5DWB00L8c_KTO1ew",
        "type": "loan",
	"content": {
             "amount", "R$ 100,00",
             "installments": "2",
             "document": "123.345.503-70"
	}
  }"

```

No exemplo acima, os campos podem ser explicados da seguinte maneira:
- `order` é número do pedido no sistema interno da empresa;
- `name` é o nome do cliente que assinará o contrato e será utilizado na criação da conta do cliente;
- `email` é o email do cliente que assinará o contrato e será utilizado na criação da conta do cliente, se o email já existir na base do VSign, uma nova conta não deve ser criada;
- `client_id` é o número secreto para a empresa informar nas requisições na API, será usado para identificar;
- `type` é o tipo de contrato que o cliente irá assinar.

**Comment by kairon-v** [comment]
Sugiro utilizar a gem `devise` para autenticação de usuário.

**Comment by MarcosFloresta** [comment]
Como configuro a `devise` para implementar o último critério de aceitação?
