### ISSUE TITLE
US06 - Enviar informações de novo contrato para o usuário

### ISSUE THREAD

**Issue by kairon-v** [fga-eps-mds/2019.2-Vsign#56]
**Descrição**
Como usuário, desejo receber informações via email de novos contratos para assinatura.

**Critérios de aceitação**
- [x] Criar template de email no SendGrid;
- [ ] O corpo do email deve possuir um botão para que leva o usuário direto a página para assinatura do contrato, sem a necessidade de logar com email e senha;
- [ ] Enviar as informações via email.

**Comment by MarcosFloresta** [comment]
Foi criado o template de email para novos contratos

**Comment by MarcosFloresta** [comment]
<img width="1279" alt="Captura de Tela 2019-09-24 às 17 25 24" src="https://user-images.githubusercontent.com/48621296/65547723-6d5f7300-def0-11e9-8dbc-312c13799766.png">

**Comment by Foxtrot40** [comment]
Eu criei toda a parte de ter um token encriptado para o contrato poder ser assinado sem login, apenas tendo acesso à esse token, mas eu não sei no frontend, onde começa a ser assinado o contrato.
