### ISSUE TITLE
US09 - Integrar SendGrid para envio de emails

### ISSUE THREAD

**Issue by kairon-v** [fga-eps-mds/2019.2-Vsign#58]
**Descrição**
Como desenvolvedor, desejo realizar a integração do SendGrid na API do VSign para envio de emails.

**Critérios de aceitação**
- [x] Criar conta SendGrid (EPS);
- [x] Utilizar gem https://github.com/sendgrid/sendgrid-ruby (MDS).

**Comment by kairon-v** [comment]
Conta foi criada. Ao iniciar a integração, por gentileza, solicitar a chave da API.

**Comment by MarcosFloresta** [comment]
Precisa completar esta isseu #58 para implementar a isseu US04 #53?

**Comment by kairon-v** [comment]
Como vai fazer envio de email, o ideal é que sim.
