### ISSUE TITLE
Criar team no Slack

### ISSUE THREAD

**Issue by kairon-v** [fga-eps-mds/2019.2-Vsign#6]
### Descrição

Criar team no slack para adicionar os membros do projeto, assim como o Fabrício da BxBlue.

**Comment by caue96** [comment]
Time no slack criado, todos os membros do time já receberam os convites e o slack já foi todo configurado. GitHub (para atualizações no repositório do projeto), Google Calendar(para agendar no calendário de todos do time as reuniões), Google Drive (para atualizações de arquivos do Drive), Kyber (para standup meetings eventuais não presenciais, polls, mensagens com horário programado, entre diversas outras fucinonalidades) e Zoom (para iniciar reuniões mais rapidamente entre a equipe e o cliente) foram todos configurados nos canais do Slack conforme a necessidade do time.
