### ISSUE TITLE
US12 - Apresentar lista de contratos do usuário

### ISSUE THREAD

**Issue by kairon-v** [fga-eps-mds/2019.2-Vsign#62]
**Descrição**
Como usuário, desejo visualizar a lista de contratos disponíveis para minha conta para que eu possa acompanhar o andamento das validações.

**Critérios de aceitação**
- [ ] A consulta dos contratos deve ser feita via GraphQL;
- [ ] Utilizar o protótipo como referência para criação da lista;

**Comment by Foxtrot40** [comment]
Não tem model de contratos no backend, não da pra fazer a consulta lá. A menos que mude a US pra abranger essa issue de criar o model de contrato também. @kairon-v

**Comment by kairon-v** [comment]
@Foxtrot40 você pode utilizar mocks enquanto a API não está pronta.
