### ISSUE TITLE
Reportar erro no roteiro

### ISSUE THREAD

**Issue by kairon-v** [fga-eps-mds/2019.2-Vsign#64]
**Descrição**<br>
Como usuário, desejo reportar erros no roteiro do meu contrato para que a empresa possa realizar a correção.

**Critérios de aceite**
- [x] Antes da tela de instruções de assinatura, deve ter uma tela que apresente o roteiro completo.
- [x] Opção para o usuário reportar o erro no roteiro. Pode ser um botão com o texto "Reportar Erro";
- [x] Apresentar um campo para livre escrita para que o usuário possa dizer o que está errado.
- [x] Notificar empresa `Company` via email, relatando o erro reportado pelo usuário.
- [x] Armazenar no banco de dados o erro relatado pelo usuário.

**Comment by williamtpv** [comment]
### Layout da página

![image](https://user-images.githubusercontent.com/49319276/65280581-0bc19200-db07-11e9-94ca-768979256366.png)

**Comment by williamtpv** [comment]
@kairon-v, @Foxtrot40  quanto ao campo de escrita, é melhor fazer ele aparecer dentro da propria pagina ou abrir em uma nova janela?

**Comment by williamtpv** [comment]
### Espaço para reportar erros
![image](https://user-images.githubusercontent.com/49319276/65367918-84137a80-dc0f-11e9-905d-9eafcc6cb773.png)

**Comment by williamtpv** [comment]
### Novo layout

![image](https://user-images.githubusercontent.com/49319276/66363074-5b9fb600-e95b-11e9-9654-6dce4cf9be8c.png)

**Comment by williamtpv** [comment]
### Layout padronizado

![image](https://user-images.githubusercontent.com/49319276/66373248-949d5200-e97e-11e9-915b-a578dc50163c.png)

**Comment by williamtpv** [comment]
### Modal para reportar erro

![image](https://user-images.githubusercontent.com/49319276/66373794-d8448b80-e97f-11e9-849e-42343c6c5abe.png)

**Comment by kairon-v** [comment]
@williamtpv o modelo para a tela que eu tinha sugerido é esse abaixo:
![tela-informacoes-contrato](https://user-images.githubusercontent.com/6243672/66664395-d2baa000-ec22-11e9-9c11-4f01dd1f3da7.png)

**Comment by kairon-v** [comment]
Corrigido em #163 .
