### ISSUE TITLE
US15 - Revisar vídeo de assinatura

### ISSUE THREAD

**Issue by kairon-v** [fga-eps-mds/2019.2-Vsign#66]
**Descrição**<br>
Como usuário, quero revisar meu vídeo de assinatura para verificar se está como o esperado.

**Critérios de aceitação**
- [x] Permitir o usuário assistir o vídeo gravado;
- [x] Mostrar o roteiro completo para o usuário (para que o usuário veja se o que foi falado no vídeo está de acordo com o roteiro);
- [x] Permitir que o usuário finalize a assinatura (preparação para upload do vídeo e imagens);
- [x] Permitir que o usuário reinicie o processo de assinatura.

**Comment by ViniciusPuerto** [comment]
### Implementaremos a tela de revisar da seguinte forma

![telaDeRevisao](https://user-images.githubusercontent.com/26886701/65277954-7079ee00-db01-11e9-898a-47d71f28a869.png)

**Comment by ViniciusPuerto** [comment]
### Link utilizado 
O [Link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#Attributes) está sendo usado como guia para a reprodução do vídeo logo após gerarmos a URL a partir da função: `const url = URL.createObjectURL(signatureVideo);`

**Comment by marcosgtavares** [comment]
### Linha adicionada para a compatibilidade do reprodutor com chrome
 A seguinte linha foi adicionada ao codigo para o reprodutor de video utilizado ser compativel com o chrome: `var createObjectURL = (window.URL || window.webkitURL || {}).createObjectURL || function(){};`
