### ISSUE TITLE
US18 - Melhorar Interface de Usuário

### ISSUE THREAD

**Issue by caue96** [fga-eps-mds/2019.2-Vsign#80]
**Descrição**<br>
Como usuário eu quero poder ter acesso facilmente as funcionalidades.<br>

**Critérios de aceite**
- [x] Todas as páginas do sistema podem ser acessadas com no máximo 3 cliques;
- [x] Páginas e objetos responsivos.<br>

**Comment by ViniciusPuerto** [comment]
# Melhoria na tela de gravar o vídeo

Fizemos uma série de ajustes no design da tela de gravar video para que melhorasse a experiência de usuário, clique na imagem para ver em tamanho real.

![Captura de Tela 2019-10-03 às 02 02 00](https://user-images.githubusercontent.com/26886701/66100638-1574dc00-e582-11e9-90dd-6e7da99b11a9.png)
