### ISSUE TITLE
Criar Roadmaps

### ISSUE THREAD

**Issue by caue96** [fga-eps-mds/2019.2-Vsign#86]
**Descrição**<br>
Fazer roadmaps dos papeis (Arquiteto, DevOps, Product Owner e Scrum Master) e do projeto.

**Comment by caue96** [comment]
Roadmap do projeto terá participação de todo time (EPS e MDS).

**Comment by thiagorpereira** [comment]
Roadmap do projeto em desenvolvimento; 

![photo4924764013498312744](https://user-images.githubusercontent.com/26577467/65728363-1513a700-e091-11e9-951b-804f65243fdc.jpg)

**Comment by caue96** [comment]
Roadmaps esperando aprovação no pull request #88
