### ISSUE TITLE
Criar Diagrama de Casos de Uso

### ISSUE THREAD

**Issue by caue96** [fga-eps-mds/2019.2-Vsign#94]
**Descrição**<br>
Será feito um diagrama de caso de uso para que toda a equipe consiga visualizar as funcionalidades propostas para o sistema Vsign, enxergando todas as sequências de eventos dos usuários no sistema.

**Comment by williamtpv** [comment]
### Primeira versão do diagrama de casos de uso
![image](https://user-images.githubusercontent.com/49319276/66042971-460e3480-e4f4-11e9-86f0-d6f2cf28c851.png)
